Etna 797
tinkoff-ai/etna-ts pull request #110
Opened 2021-09-28 13:58 UTC by alex-hse-repository

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna-ts/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna-ts/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes

Add Clustering
## Related Issue

## Closing issues

2021-09-29 12:07 UTC, alex-hse-repository commented
Note: The DistanceMatrix version for new architecture shows the same time as the old one in computing distance matrix

2021-09-29 13:49 UTC, martins0n requested changes
- We should add basic example to DTWClustering and EuclideanClustering class docstrings.
- np.array to np.ndarray in type
- check docsting for proper `Result` section. Sometimes typing is missing.

2021-10-01 14:54 UTC, martins0n requested changes

2021-10-01 14:54 UTC, martins0n commented on etna/clustering/distances/distance_matrix.py
> +        logger_id = tslogger.add(ConsoleLogger())
You shouldn't do this. Tslogger is as global object and all handlers've added already.
`        tslogger.start_experiment()` and this look at code examples https://github.com/tinkoff-ai/etna-ts/blob/51afbc2df6d046e3c2ab9b102f50fc7c83529f5a/etna/datasets/tsdataset.py#L122

2021-10-04 08:33 UTC, martins0n approved these changes
👍

2021-10-04 08:34 UTC, merged