add ranks
tinkoff-ai/etna-ts pull request #268
Opened 2021-11-10 12:58 UTC by Ama16

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna-ts/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna-ts/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes

## Related Issue

## Closing issues

2021-11-10 13:59 UTC, alex-hse-repository requested changes

2021-11-10 13:59 UTC, alex-hse-repository commented on etna/analysis/feature_relevance/relevance.py
> +    def _get_ranks(self, table) -> pd.DataFrame:
Add also typing to `table` pls

2021-11-10 13:59 UTC, alex-hse-repository commented on etna/analysis/feature_relevance/relevance.py
> +        rank_table = table.apply(lambda x: pd.Series(scipy.stats.rankdata(x.values), index=x.index), axis=1)
```suggestion
       rank_table =  pd.DataFrame(scipy.stats.rankdata(rank_table, axis=1), columns= rank_table.columns, index= rank_table.index)
```

2021-11-10 13:59 UTC, alex-hse-repository commented on etna/analysis/feature_relevance/relevance.py
> +            rank_table = -1 * (rank_table - rank_table.shape[1] - 1)
Why not just `table *=-1` before ranking?

2021-11-10 13:59 UTC, alex-hse-repository commented on etna/transforms/feature_importance.py
> +        relevance_table = self.relevance_method(
It is better to use keyword arguments hear(imho)

2021-11-10 13:59 UTC, alex-hse-repository commented on tests/test_analysis/test_feature_relevance/test_relevance.py
> +def test_relevance_table_ranks(simple_df_relevance):
Better to make a fixture for the table with ranks and test the method in two cases of `greater_is_better`

2021-11-10 13:59 UTC, alex-hse-repository commented on tests/test_transforms/test_feature_importance_transform.py
>  def test_mrmr_right_len(relevance_method, clustering_method, top_k, ts_with_regressors):
Better to use keyword arguments, fix it pls in this file

2021-11-12 09:50 UTC, julia-shenshina commented on etna/analysis/feature_relevance/relevance.py
> +    def __call__(self, df: pd.DataFrame, df_exog: pd.DataFrame, return_ranks: bool, **kwargs) -> pd.DataFrame:
shouldn't we add `False` as default value for `return_ranks`?

2021-11-15 07:32 UTC, julia-shenshina submitted a review, later dismissed

2021-11-15 07:37 UTC, alex-hse-repository submitted a review, later dismissed

2021-11-15 09:33 UTC, alex-hse-repository approved these changes

2021-11-15 09:45 UTC, merged